{{- if $.Values.env_variables }}
{{ include "nops-k8s-agent.validateEnvVariables" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
{{- range $key, $value := $.Values.env_variables }}
  {{ if $value }}
   {{ $key }}: "{{ $value }}"
   {{end}}
  {{- end }}
{{- end }}

