{{- if and .Values.prometheus.kubeStateMetrics.podSecurityPolicy.enabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | indent 4 }}
{{- if .Values.prometheus.kubeStateMetrics.podSecurityPolicy.annotations }}
  annotations:
{{ toYaml .Values.prometheus.kubeStateMetrics.podSecurityPolicy.annotations | indent 4 }}
{{- end }}
spec:
  privileged: false
  volumes:
    - 'secret'
{{- if .Values.prometheus.kubeStateMetrics.podSecurityPolicy.additionalVolumes }}
{{ toYaml .Values.prometheus.kubeStateMetrics.podSecurityPolicy.additionalVolumes | indent 4 }}
{{- end }}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
