{{- if $.Values.nopsAgent.env_variables }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
{{- range $key, $value := $.Values.nopsAgent.env_variables }}
  {{ if $value }}
   {{ $key }}: "{{ $value }}"
   {{end}}
  {{- end }}
{{- end }}

