{{- if .Values.prometheus.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.server" . }}
  namespace: {{ include "prometheus.namespace" . }}
  annotations:
{{ toYaml .Values.prometheus.server.serviceAccounts.server.annotations | indent 4 }}
{{- if kindIs "bool" .Values.prometheus.server.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.prometheus.server.automountServiceAccountToken }}
{{- else if kindIs "bool" .Values.prometheus.serviceAccounts.server.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.prometheus.serviceAccounts.server.automountServiceAccountToken }}
{{- end }}
{{- end }}
