{{- if not .Values.prometheus.server.statefulSet.enabled -}}
{{- if .Values.prometheus.server.persistentVolume.enabled -}}
{{- if not .Values.prometheus.server.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .Values.prometheus.server.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.prometheus.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
    {{- with .Values.prometheus.server.persistentVolume.labels }}
       {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "prometheus.server.fullname" . }}
  namespace: {{ include "prometheus.namespace" . }}
spec:
  accessModes:
{{ toYaml .Values.prometheus.server.persistentVolume.accessModes | indent 4 }}
{{- if .Values.prometheus.server.persistentVolume.storageClass }}
{{- if (eq "-" .Values.prometheus.server.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.prometheus.server.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
{{- if .Values.prometheus.server.persistentVolume.volumeBindingMode }}
  volumeBindingMode: "{{ .Values.prometheus.server.persistentVolume.volumeBindingMode }}"
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.prometheus.server.persistentVolume.size }}"
{{- if .Values.prometheus.server.persistentVolume.selector }}
  selector:
  {{- toYaml .Values.prometheus.server.persistentVolume.selector | nindent 4 }}
{{- end -}}
{{- if .Values.prometheus.server.persistentVolume.volumeName }}
  volumeName: "{{ .Values.prometheus.server.persistentVolume.volumeName }}"
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
