apiVersion: v1
kind: Service
metadata:
  name: {{ include "nops-k8s-agent.fullname" . }}
  labels:
    {{- include "nops-k8s-agent.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: app
  selector:
    {{- include "nops-k8s-agent.selectorLabels" . | nindent 4 }}
    app: api
