{{ if .Values.nopsAgent.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nops-k8s-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nops-k8s-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "nops-k8s-agent.fullname" . }}
    namespace: nops-k8s-agent
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nops-k8s-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nops-k8s-agent
subjects:
  - kind: ServiceAccount
    name: deafult
    namespace: nops-k8s-agent
{{ end }}