{{- if and .Values.prometheus.rbac.create (empty .Values.prometheus.server.namespaces) (empty .Values.prometheus.server.useExistingClusterRoleName) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ include "prometheus.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName.server" . }}
    namespace: {{ include "prometheus.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus.clusterRoleName" . }}
{{- end }}
